"""empty message

Revision ID: 44769b5cd09e
Revises: 67ec76fa1f4a
Create Date: 2022-08-03 16:58:21.019690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44769b5cd09e'
down_revision = '67ec76fa1f4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('seeking_talent', sa.Boolean(), nullable=True))
    op.add_column('venues', sa.Column('seeking_description', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'seeking_description')
    op.drop_column('venues', 'seeking_talent')
    # ### end Alembic commands ###
