"""empty message

Revision ID: 67ec76fa1f4a
Revises: dde25ac8c50d
Create Date: 2022-08-03 16:50:15.617757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67ec76fa1f4a'
down_revision = 'dde25ac8c50d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('website_link', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'website_link')
    # ### end Alembic commands ###
